easy_admin:
    site_name: 'MyCouturier BackEnd'
    design:
      assets:
        # all kinds of assets are supported and linked accordingly
        css:
          # - '//example.org/css/admin1.css'
        js:
          # - '//example.org/js/admin1.js'
    list:
      max_results: 10
    entities:
       # List the entity class name you want to manage
      
      User:
        class: App\Entity\User

      UserApp:
        class: App\Entity\UserApp

      ContactUs:
        class: App\Entity\ContactUs

      Retouching:
        class: App\Entity\Retouching
        list: 
          fileds: ['Type', { property: 'CategoryRetouching', label: 'type'}]
      
      PriceGrid:
        class: App\Entity\PriceGrid
      
      Prestations:
        class: App\Entity\Prestations

      
