easy_admin:
   entities:
      # List the entity class name you want to manage
      #  - App\Entity\Product
      #  - App\Entity\Category
       - App\Entity\UserApp
       - App\Entity\Comments
       - App\Entity\Prestation
       - App\Entity\PrestationStatus
       - App\Entity\Retouching
       - App\Entity\RetouchingType
